### ISSUE TITLE
Data object access in policy always results in status "allowed"

### ISSUE THREAD

**Issue by Sir-Jacques** [open-policy-agent/kube-mgmt#101]
Hey,

While deploying the opa helm chart (1.14.6) on our cluster we ran into an issue we haven't been able to solve during the last couple of days. All resources (except our policy cm) are deployed using this values.yaml:

````
opa:
  opa: false 
  imageTag: 0.30.2
  logLevel: debug

  admissionControllerFailurePolicy: Fail
  admissionControllerNamespaceSelector:
    matchExpressions:
      - {key: openpolicyagent.org/webhook, operator: NotIn, values: [ignore]}

  admissionControllerRules:
    - operations: ["CREATE","UPDATE"]
      apiGroups: ["*"]
      apiVersions: ["*"]
      resources: ["ingressgates"]
      scope: "*"
    - operations: ["CREATE","UPDATE"]
      apiGroups: ["*"]
      apiVersions: ["*"]
      resources: ["ingresses"]
      scope: "*"
    - operations: ["CREATE","UPDATE"]
      apiGroups: ["*"]
      apiVersions: ["*"]
      resources: ["services"]
      scope: "*"

  imagePullSecrets:
  - dockerhub-imagepullsecret

  mgmt:
    configmapPolicies:
      enabled: true
      namespaces: [open-policy-agent]
      requireLabel: true
    data:
      enabled: true

  rbac:
    create: true
    rules:
      cluster: 
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - list
        - watch
        - patch
````

Then I inserted this policy into the same namespace to test the functionality (should deny ALL ingresses):
````
apiVersion: v1
data:
  deny-all-ingress.rego: |
    package kubernetes.admission
    deny[msg] {
        input.request.kind.kind == "Ingress"
        msg := sprintf("INGRESS DENIED!")
    } 
kind: ConfigMap
metadata:
  labels:
    openpolicyagent.org/policy: rego
  name: deny-all-ingress
````

After attempting to insert an ingress into the cluster we recieve this message from kubectl:
````
Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "webhook.openpolicyagent.org": the server could not find the requested resource
````

I find this log in the opa container:
````
[INFO] Received request.
  req_params = |
      {
        "timeout": [
          "30s"
        ]
      }
  client_addr = "10.110.0.2:25765"
  req_id = 8
  req_method = "POST"
  req_path = "/"
  req_body = <ingress data omitted>

[INFO] Sent response.
  req_method = "POST"
  req_path = "/"
  resp_status = 404
  resp_bytes = 99
  resp_duration = 7.827122
  resp_body = |
      {
        "code": "undefined_document",
        "message": "document missing or undefined: data.system.main"
      }
  client_addr = "10.110.0.2:25765"
  req_id = 8

````

These log lines suggest the webhook is working. Unfortunately we haven't been able to find their cause. Is there anything wrong with our values.yaml? Or is there anything obvious we're overlooking?

Kind regards,
Jacco

**Comment by ashutosh-narkar** [comment]
You'll have to specify the `default_decision` in your `opa` config to point to your policy. Or define a policy at `data.system.main` which then calls your policy. [This](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/) tutorial has an example of the latter. When the k8s API server does a `POST` on `/`,  OPA looks for a policy decision at  `data.system.main` by default.

**Comment by Sir-Jacques** [comment]
Thanks for your reply! 

In that tutorial they insert this default policy 'manually'. Is there a way to deploy it from the helm chart? I've applied that ConfigMap template to our cluster (using the correct namespace), but that did not work.

Also, does the default policy from the tutorial automatically trigger other policies? Or should we add them to the default policy manually?

Kind regards,
Jacco

**Comment by ashutosh-narkar** [comment]
> Also, does the default policy from the tutorial automatically trigger other policies?

Yes.

>  I've applied the ConfigMap template directly to our cluster (using the correct namespace), but that did not work.

You should either change the `default_decision` in your `opa` config or structure your policy similar to the tutorial.

**Comment by Sir-Jacques** [comment]
Hey,

First of all, many thanks for pointing us in the right direction! It turned out that I forgot to add the policy label to the default_decision policy ConfigMap (because of 'requireLabel'), but now I can use my debug policy that denies all ingresses. 

However, when I try to use the data object inside a policy it always responds with "allowed". In my helm values.yaml I've set opa.mgmt.data.enabled to be true. This, indeed, changed the deployment arguments for the container. I do not see any additional logs in my containers (despite loglevel 'info').

We suspected an issue with the rights of our ServiceAccount/ClusterRole but those are deployed from the helm chart (and should thus probably be ok?).

Is it expected behavior that an exception in the deny-block results in an "allowed" status? And am I still missing something here (which causes this log-less exception)? 

Yours sincerely,
Jacco

**Comment by ashutosh-narkar** [comment]
You can turn on debug logging in OPA using the log level `debug`. You can also turn on [console decision logging](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#local-decision-logs) to get more information.

Also have you [unit tested](https://www.openpolicyagent.org/docs/latest/policy-testing/) your policy ? We recommend you do that before running it in your setup. It helps debugging.

**Comment by Sir-Jacques** [comment]
I'm currently using the example ingress-conflicts policy (https://play.openpolicyagent.org/). The policy was validated using the rego playground, and behaves correctly (in the playground). But as soon as I insert an existing hostname into the cluster it gets "allowed".

I suspect the data object is empty (thus resulting in 0 conflicts), but haven't been able to verify this (decision_logging doesn't provide the data object). Could this be due to RBAC?

The cluster role and binding deployed from the chart look like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: opa
    argocd.argoproj.io/instance: opa
    chart: opa-1.14.6
    component: mgmt
    heritage: Helm
    release: opa
  name: opa-mgmt
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: opa
    argocd.argoproj.io/instance: opa
    chart: opa-1.14.6
    component: mgmt
    heritage: Helm
    release: opa
  name: opa-mgmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opa-mgmt
subjects:
  - kind: ServiceAccount
    name: opa
    namespace: open-policy-agent
```

We have also disabled the "opa" object in our values.yaml because we could not get the default default_decision to work using the default values. Could that be causing any issues with the data object?

Kind regards,
Jacco
