### ISSUE TITLE
Trouble replicating CRD resources in kube-mgmt

### ISSUE THREAD

**Issue by somebodywithaninterestingface** [open-policy-agent/kube-mgmt#24]
Hi everyone,

I'm having problems caching crds that i created into kube-mgmt
say i have a CRD like such
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: examples.examples.example.com
spec:
  group: examples.example.com
  version: v1
  names:
    kind: Example
    plural: examples
  scope: Cluster
`
```

I'm trying to import it as 
"--replicate-cluster=examples.example.com/v1/examples"

however this does not work.
Any suggestions?
