### ISSUE TITLE
Helm chart with auth enabled

### ISSUE THREAD

**Issue by EdwardCooke** [open-policy-agent/kube-mgmt#265]
I'm using the helm chart and trying to keep authentication enabled. What I'm running into is that I have to know the token in order to use it. I was hoping to have a separate token for the Kubernetes API to hit OPA and keep the token for kube-mgmt separate.

I can't find any examples of how to do this.

If I disable authentication my policy returns expected data, if I have authentication enabled I get an unauthorized response.

My values.yaml
```yaml
opa:
  decision_logs:
    console: true

authz:
  enabled: true #false

certManager:
  enabled: true
  rootCACertificateDuration: 87600h # 10 years
  serviceCertificateDuration: 8760h # 1 year

prometheus:
  enabled: true
image:
  tag: 0.69.0
mgmt:
  namespaces: []
  replicate:
    cluster:
    - v1/namespaces
    - apps/v1/deployments
    - apps/v1/statefulsets
    - apps/v1/daemonsets
    - batch/v1/cronjobs
    - batch/v1/jobs

replicas: 1
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: "app"
          operator: In
          values:
          - opa
      topologyKey: "kubernetes.io/hostname"
tolerations:
- key: "node-role.kubernetes.io/control-plane"
  effect: NoSchedule
  operator: Exists
nodeSelector:
  node-role.kubernetes.io/control-plane: ""

rbac:
  extraRules:
  - apiGroups:
    - v1
    resources:
    - namespaces
    verbs:
    - get
    - list
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    - daemonsets
    verbs:
    - get
    - list
  - apiGroups:
    - batch
    resources:
    - cronjobs
    - jobs
    verbs:
    - get
    - list
 ```

My configmap with policies
```yaml
apiVersion: v1
data:
  policy1: |
    package example

    import rego.v1
    default allow := false
    allow if {
      creditor_is_valid
    }
    creditor_is_valid if 1 == 1
    doc := input.xyz
  policy2: |
    package example.authz
    default allow := true
kind: ConfigMap
metadata:
  labels:
    openpolicyagent.org/policy: rego
  name: test
  namespace: opa-auth-system
```

I've tried a number a different variations of the config map policy, checking the identity, not checking the identity, just setting allow := true, nothing seems to get me past this error
```json
{
  "code": "unauthorized",
  "message": "request rejected by administrative policy"
}
```

Here's my curl request
```shell
curl -H "Authorization: Bearer secret" -H "Content-Type: application/json" https://localhost:8181/v0/data/example -k -X POST -d '{ "xyz": "def" }'
```

I've also tried
```shell
curl -H "Authorization: Bearer secret" -H "Content-Type: application/json" https://localhost:8181/v0/data/example/doc -k -X POST -d '{ "xyz": "def" }'
```
and
```shell
curl -H "Authorization: Bearer secret" -H "Content-Type: application/json" https://localhost:8181/v0/data/example/authz-k -X POST -d '{ "xyz": "def" }'
```

**Comment by EdwardCooke** [comment]
If I use the token for kube-mgmt then it works. I just want to use a separate token. Least privileges and all that.

**Comment by eshepelyuk** [comment]
Hello

TBH i was unable to understand your goal and the issue you're experiencing.

But maybe you see the error because you use incorrect OPA REST API path, i.e. `v0` instead `v1` ?
https://www.openpolicyagent.org/docs/latest/rest-api/#data-api

**Comment by EdwardCooke** [comment]
I don't want to use the same token that I use for kube-mgmt for the kubernetes api server. Also, the v1 requires input data to be wrapped around the `input` field, it also returns the result wrapped with `result`. Which as far as I'm aware that isn't going to work for Kubernetes.

I want to use the authentication to prevent people from adding or modifying policies.

I'm thinking I need to somehow customize the authz policy that is created by the helm chart. However, anytime I try and do that I get a 400 back.

However, I think that 400 was due to the older version of OPA and the examples I found were importing `rego.v1`. I was able to add a second auth policy using this config map and it works now :)

```yaml
apiVersion: v1
data:
  policy1: |
    package example

    import rego.v1
    doc := input
  policy2: |
    package system.authz
    import rego.v1
    allow if { input.identity == "secret" }
kind: ConfigMap
metadata:
  labels:
    openpolicyagent.org/policy: rego
  name: test
  namespace: opa-auth-system
```

With this curl request
```shell
curl -H "Authorization: Bearer secret" -H "Content-Type: application/json" https://localhost:8181/v0/data/example -k -X POST -d '{ "xyz": "def" }'
```

Returns as expected
```json
{"doc":{"xyz":"def"}}
```

So hopefully this will help someone in the future.
