### ISSUE TITLE
--policies=* does not appear to be working

### ISSUE THREAD

**Issue by stefansedich** [open-policy-agent/kube-mgmt#55]
Given the following deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opa
  namespace: opa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa
        args:
        - "run"
        - "--server"
        ports:
        - name: http
          containerPort: 8181
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.10
        args:
          - --enable-policies=true
          - --policies=*
          - --require-policy-label=true
```

And given the following configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: test
  labels:
    openpolicyagent.org/policy: rego
data:
  test.rego: |
    package kubernetes

    example = "Hello, Kubernetes!"
```

kube-mgmt does not appear to be loading the configmap at all, if I were to set `--policies=test` with an explicit namespace it will load the configmaps fine. 

I was under the impression that `--policies=*` will load from any namespace?
