### ISSUE TITLE
Can not load configmap data from a namespace with a dash in it's name

### ISSUE THREAD

**Issue by gregsidelinger** [open-policy-agent/kube-mgmt#67]
After following the instructions for [json-loadin](https://github.com/open-policy-agent/kube-mgmt#json-loading) I could not access the data being loaded if the namespace contained a dash. I've using kube-mgmt v0.11.

Here is an example configmap modified from the example in the docs I was using for testing.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-data
  namespace: opa-data
  labels:
    openpolicyagent.org/data: opa
data:
  x.json: |
    {"a": [1,2,3,4]}
```

When applied I should see a log like so in OPA however there are no logs related to the data.
```
[INFO] Sent response.
  resp_bytes = 0
  resp_duration = 0.443091
  resp_body = ""
  client_addr = "127.0.0.1:38344"
  req_id = 68
  req_method = "PUT"
  req_path = "/v1/data/opa-data/hello-data/x.json"
  resp_status = 204

[INFO] Received request.
  req_id = 69
  req_method = "PUT"
  req_path = "/v1/data/opa-data/hello-data/x.json"
  req_body = |
      {"a":[1,2,3,4]}
```

And the openpolicyagent.org/policy-status annotation never gets created or updated on the configmap.  The pod has cluster wide access to read/update config maps.  Everything works as expected if I switch from a namespace called opa-data to one called opa.

**Comment by patrick-east** [comment]
Thanks for filing the issue!

Can you share the `kube-mgmt` logs and deployment configuration (in particular the arguments passed in for `--policies`)?

**Comment by gregsidelinger** [comment]
Here are the logs, nothing special is ever printed.
```
time="2020-05-04T20:34:47Z" level=warning msg="First line of log stream."
time="2020-05-04T20:34:47Z" level=info msg="Syncing v1/namespaces."
time="2020-05-04T20:34:47Z" level=info msg="Listed v1/namespaces and got 24 resources with resourceVersion 121047049. Took 17.147992ms."
time="2020-05-04T20:34:47Z" level=info msg="Loaded v1/namespaces resources into OPA. Took 2.192824ms. Starting watch at resourceVersion 121047049."
time="2020-05-04T21:28:15Z" level=info msg="Sync channel for v1/namespaces closed. Restarting immediately."
time="2020-05-04T21:28:15Z" level=info msg="Syncing v1/namespaces."
time="2020-05-04T21:28:15Z" level=info msg="Listed v1/namespaces and got 25 resources with resourceVersion 121072940. Took 5.95692ms."
time="2020-05-04T21:28:15Z" level=info msg="Loaded v1/namespaces resources into OPA. Took 2.492351ms. Starting watch at resourceVersion 121072940."
time="2020-05-04T22:23:05Z" level=info msg="Sync channel for v1/namespaces closed. Restarting immediately."
time="2020-05-04T22:23:05Z" level=info msg="Syncing v1/namespaces."
time="2020-05-04T22:23:05Z" level=info msg="Listed v1/namespaces and got 25 resources with resourceVersion 121099510. Took 5.770862ms."
time="2020-05-04T22:23:05Z" level=info msg="Loaded v1/namespaces resources into OPA. Took 3.048985ms. Starting watch at resourceVersion 121099510."
```

Here is my full deployment generated using the stable/opa helm chart.  Policies is currently set to false but it was true at one point in time and I turned it off since I was not using it currently.  Also it looks like I'm using v0.10 in this deployment.  I did try v.0.11 too.  I also removed the policies from the deployment to cut out a 100ish lines of an echo to a /bootstrap file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-mutating
  labels:
    app: opa-mutating
    chart: "opa-1.13.5"
    release: "opa-mutating"
    heritage: "Tiller"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opa-mutating
  template:
    metadata:
      annotations:
        checksum/certs: 7c150ed8d35c0d58ad88540bf343e55ce5a3314819fd099db9f84cb1d2cd89ab
      labels:
        app: opa-mutating
      name: opa-mutating
    spec:
      priorityClassName: cloud-platform-critical
      initContainers:
        - name: initpolicy
          image: openpolicyagent/kube-mgmt:0.10
          imagePullPolicy: IfNotPresent
          resources:
            {}
          command:
          - /bin/sh
          - -c
          - |
            tr -dc 'A-F0-9' < /dev/urandom | dd bs=1 count=32 2>/dev/null > /bootstrap/mgmt-token
            TOKEN=`cat /bootstrap/mgmt-token`
            cat > /bootstrap/authz.rego <<EOF
            package system.authz
            default allow = false
            # Allow anonymous access to the default policy decision.
            allow { input.path = [""]; input.method = "POST" }
            allow { input.path = [""]; input.method = "GET" }
            # This is only used for health check in liveness and readiness probe
            allow { input.path = ["health"]; input.method = "GET" }
            allow { input.identity == "$TOKEN" }
            EOF
          volumeMounts:
            - name: bootstrap
              mountPath: /bootstrap
      containers:
        - name: opa
          image: openpolicyagent/opa:0.15.1
          imagePullPolicy: IfNotPresent
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:443"
            - "--log-level=error"
            - "--log-format=text"
            - "--authentication=token"
            - "--authorization=basic"
            - "--ignore=.*"
            - "--addr=http://127.0.0.1:8181"
            - "/bootstrap"
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
            - name: bootstrap
              readOnly: true
              mountPath: /bootstrap
          readinessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 30

          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 30
        - name: mgmt
          image: openpolicyagent/kube-mgmt:0.10
          imagePullPolicy: IfNotPresent
          args:
            - --opa-auth-token-file=/bootstrap/mgmt-token
            - --opa-url=http://127.0.0.1:8181/v1
            - --replicate-path=kubernetes
            - --enable-data=true
            - --enable-policies=false
            - --replicate-cluster=v1/namespaces
          volumeMounts:
            - name: bootstrap
              readOnly: true
              mountPath: /bootstrap
      serviceAccountName: opa-mutating
      volumes:
        - name: certs
          secret:
            secretName: opa-mutating-cert
        - name: bootstrap
          emptyDir: {}
```
